# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-03 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180830_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_active',
            field=models.BooleanField(default=False, verbose_name='邮箱验证状态'),
        ),
    ]
